### ISSUE TITLE
why i can use this web

### ISSUE THREAD

**Issue by 0891679592** [walfie/gbf-raidfinder#101]
![image](https://cloud.githubusercontent.com/assets/20974311/21356969/1b671a94-c706-11e6-9873-4993d11042c5.png)

it never change from this

**Comment by walfie** [comment]
it's an issue with the way certain ISPs handle websocket connections on port 80.

See this comment for details. https://github.com/walfie/gbf-raidfinder/issues/87#issuecomment-257725910

**Comment by walfie** [comment]
you can try using this version: https://gbf-raidfinder.la-foret.me/
