### ISSUE TITLE
iOS Safari clipboard copy

### ISSUE THREAD

**Issue by luminairre** [walfie/gbf-raidfinder#111]
On iOS Safari (10.3, since 10.0)

* Tapping a Tweet does not copy raid code to clipboard
* Tapping a Tweet zooms to the pseudo input element

**Comment by walfie** [comment]
So I actually don't have an iOS device to test on.

Can someone confirm whether the following example copies text to the clipboard on iOS?
http://output.jsbin.com/vorofub

**Comment by luminairre** [comment]
Nope it didn't work, same problem as what I have described, here's a few scripts that are working:

* https://clipboardjs.com
* http://www.seabreezecomputers.com/tips/copy2clipboard.htm
* http://stackoverflow.com/a/41267511

As for the zoom, iOS device zooms in when you focus on input (for accessibility reasons they say..). [This is a long thread about it](http://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone/), but in the newer iOS, you need to use the script that disables zoom while on focus (and enable them again on blur).

**Comment by walfie** [comment]
Whoops, I based it on that same stackoverflow answer but forgot to actually update the example to use the newly-added function. Can you try again?

Also updated the example to have the input element font size set to 16px

**Comment by luminairre** [comment]
Working fine! Both copy and zoom problem is fixed! Thanks!

**Comment by walfie** [comment]
🆒❗️ I will try to work on adding this functionality to the code tomorrow.
