### ISSUE TITLE
Twitter Backup Format Changed

### ISSUE THREAD

**Issue by zhurai** [walfie/gbf-raidfinder#121]
twitter formatting changed as of about an hour ago (41 min ago?) (in this software, none of the tweets are showing up. I suppose because of stricter matching...)

参加者募集！参戦ID: **id raid**

-> 

**id** :参戦ID 参加者募集！**raid**

**Comment by Zaggg** [comment]
just change the regex https://github.com/walfie/gbf-raidfinder/blob/master/stream/src/main/scala/walfie/gbf/raidfinder/StatusParser.scala#L9

**Comment by Laforeta** [comment]
I've rewritten the regex to fit the new format. It won't match anymore if the format reverts back to the old one but it should get things rolling for the moment. 

https://github.com/Laforeta/gbf-raidfinder/commit/812856b3ced7fff42214765ab7ec1bd838f4362b

N.B. Untested code

**Comment by Laforeta** [comment]
I've written a temporary fix that works for the current format, in case the format reverts to the old one it will break (again). 

https://github.com/Laforeta/gbf-raidfinder/commit/df577496cfb70c1e49c1b170435c4b90c2246e5e

Demo running at the following domain. 

https://gbf-bodge2.herokuapp.com/

Maybe Walfie can come up with a better idea in case the devs wants to mess with us again - regex isn't my forte and writing it freehand with a new beers in your system is not ideal.

**Comment by walfie** [comment]
ugh. well unfortunately I won't have the time to do a proper fix (and deploy it) until tonight at the soonest, sorry.

on the bright side, the new format actually makes the streaming filters much simpler since they're space-separated now, so I don't have to do that "Lv15,Lv20,Lv25,Lv30,..." search term hack I was doing, and I can just search ":参戦ID" or "参加者募集！"

**Comment by Laforeta** [comment]
Thanks @walfie , I've managed to get my mirror patched so people should have something to fall back to in case gbfraiders goes down. 

https://gbf-raidfinder.la-foret.me/

I really doubt the current format is intentional though - it looks really awkward and makes no grammatical sense.

**Comment by zhurai** [comment]
> I really doubt the current format is intentional though - it looks really awkward and makes no grammatical sense.

yeah ID :参戦ID makes zero sense at all

I noticed about 1hr after CCSxgbf collab was released that the raidfinders were broken (but people were actually opening lots of raids to twitter) so I opened these github issues after I figured out what went wrong.

Up to walfie, but if I notice they change the twitter format back (since this does look like a mistake), then I could open another issue (if this issue is closed)

**Comment by kiletw** [comment]
@Laforeta   It still have a bug with searching English Version backup text.
It does not work in English backup  text.

**Comment by menma1234** [comment]
My guess is that they wanted to make it easier to copy the raid code on mobile, as the in-game ID thing will ignore anything after a code that's not hexadecimal.

**Comment by zhurai** [comment]
Eh.  English backup text was changed to this format

**ID** :Battle ID
I need backup!
**RAID**

**Comment by walfie** [comment]
Updated, going to try deploying the updated version soon

**Comment by walfie** [comment]
Should be working now, in v0.3.5
