### ISSUE TITLE
About Implementation Details

### ISSUE THREAD

**Issue by mythnc** [walfie/gbf-raidfinder#125]
First, thank you for this awesome service and opensource it!

I read the `docs/implementation.md` and it is said that
> Note that we can't use 参加者募集！ -- which is in all Japanese raid tweets ......

But according to current source code, it looks like we can use `参加者募集！` directly, doesn't it?
(by #122)

It's kind of confusing.

**Comment by walfie** [comment]
True, I was too lazy to update the documentation after the change.

**Comment by walfie** [comment]
Fixed in 717c0258816ca139c06c5eb36b278aeb2481d81b
