### ISSUE TITLE
Want to know: How to track Filtered Stream in Japanese 

### ISSUE THREAD

**Issue by XinoAssassin** [walfie/gbf-raidfinder#126]
Hello walfie,
recently days I'm working on writing a RaidFinder with Node.js and I found a problem:  
How to track Twitter Stream use keyword: "参加者募集！".
Because in [Twitter official guide](https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters)#track, it says "Non-space separated languages, such as CJK are currently unsupported. " And when I use the API, it works absolutely likes what the docs said.
But when I'm reading this project's source code, I found you just set "\"参加者募集！\" OR \"I need backup!\"" as the default default search terms.(in TwitterSearcher.scala)
Could you tell me some ideas about this problem?
Thanks a lot.

**Comment by walfie** [comment]
The `"参加者募集！" OR "I need backup!"` search term is used in the search API (non real-time), which is only on startup.

The tracked keywords for the streaming part can be found in [TwitterStreamer.scala](https://github.com/walfie/gbf-raidfinder/blob/d46c7b18a577d1a64cfe48ff740996e847973e70/stream/src/main/scala/walfie/gbf/raidfinder/TwitterStreamer.scala#L14):

"参加者募集！", ":参戦ID", "I need backup!", ":Battle ID"

**Comment by XinoAssassin** [comment]
Thanks a lot. Now I know the request body to stream/filter API which contains `"track=keywords"` is just spilt by `','`.
