### ISSUE TITLE
custom subdomain not working?

### ISSUE THREAD

**Issue by CaiMiao** [walfie/gbf-raidfinder#128]
I'm trying to setup a clean build on my VPS,
everything seems ok when I directly visit 0.0.0.0:9000
but it seems not meaning to load twitter streams when I visit my subdomain for the app.
My workaround is Apache redirecting, any clue?

**Comment by walfie** [comment]
I'm not familiar with Apache or your specific redirect setup, but make sure that whatever your setup is, it can handle websockets on the same port.

**Comment by CaiMiao** [comment]
```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName sub.example.host
    ProxyPass / http://0.0.0.0:9000/
    ProxyPassReverse / http://0.0.0.0:9000/
    
    ProxyPass /ws/raids ws://0.0.0.0:9000/ws/raids
    ProxyPass /ws/raids wss://0.0.0.0:9000/ws/raids
</VirtualHost>

```
i tried to handle but it still not working...

**Comment by CaiMiao** [comment]
I'm done, solved by advancing ws proxy line.

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName sub.example.host

    ProxyPass /ws/raids ws://0.0.0.0:9000/ws/raids
    ProxyPass /ws/raids wss://0.0.0.0:9000/ws/raids

    ProxyPass / http://0.0.0.0:9000/
    ProxyPassReverse / http://0.0.0.0:9000/
</VirtualHost>

```
