### ISSUE TITLE
Not applying .scala changes on client?

### ISSUE THREAD

**Issue by CaiMiao** [walfie/gbf-raidfinder#130]
I did a image redirection [here](https://github.com/CaiMiao/gbf-raidfinder-schinese/commit/4086b9110c062be322a1de68f6b450a741c2ee29#diff-32f6c5f2ad0e7cbf58b0a82af2fe0147), set reverse proxy to ensure image resources can be correctly loaded in mainland China.

But later I found the change is not applying on my client generated by `sbt client/fastOptJS`.

Are the changes only apply on the full build of the project?
It's worrying because my vps cant't afford high resource consumption (512MB memory)...
I only have a little knowledge on Java or JavaScript things. Since I have dealt with Scala thing, I don't really want to alter the implemention by JavaScript...

**Comment by walfie** [comment]
You want to use `fullOptJS` instead of `fastOptJS` for production builds.

**Comment by CaiMiao** [comment]
Thank you for your clarifying. It works as intended.
