### ISSUE TITLE
Question regarding Twitter API 

### ISSUE THREAD

**Issue by yakrar** [walfie/gbf-raidfinder#131]
Not so much an issue, as a quick question from someone not well versed in how these types of web services work: is this program likely to be affected by the coming deprecation of Twitter's streaming API?

**Comment by walfie** [comment]
Twitter is deprecating their user streams API, which is different from the statuses/filter API used here for search terms. I'm not aware of any plans for the latter to be deprecated yet, at least.

**Comment by yakrar** [comment]
Ah. I've never worked with any of their services, so I wasn't clear on what functionality they're deprecating exactly. I just read that it was coming in August, and started to worry I'd be stuck with nothing but the ingame raid tab. 

Thanks for the quick response. I suppose I'll close this then.
