### ISSUE TITLE
[feature request] 1-click join raid using Viramate

### ISSUE THREAD

**Issue by ahxxm** [walfie/gbf-raidfinder#132]
[gbfraiders](https://www.gbfraiders.com/?raid=lvl50tiamatomega&raid=lvl60leviathanomega) provides a button to join battle(using Viramate web API): 

- join button https://github.com/ypinskiy/GBF-Raiders/blob/23ba584dbf4053619c27cc67b6731e8fd8a02de9/static/raids.js#L80
- `SendJoinCommand` implementation: https://github.com/ypinskiy/GBF-Raiders/blob/9132adeaa3695da6fb3cb399d84a8b12b5dded48/static/main.js#L771

**Comment by XinoAssassin** [comment]
You can this user script: https://greasyfork.org/en/scripts/30760-gbf-raidfinder-viramate-web-api-integration

**Comment by ahxxm** [comment]
thank you!
