### ISSUE TITLE
Cannot load bosses list

### ISSUE THREAD

**Issue by majorl3oat** [walfie/gbf-raidfinder#69]
Hi,
Thanks for making wonderful tool.

Although, I have some problem using this tool in pc.
After click "+" Button at bottom right cornor, I saw empty list of bosses list.
Chrome's Developer Tool shows as below

```
WebSocketClient.scala:37 
WebSocket connection to 'ws://gbf-raidfinder.aikats.us/ws/raids?keepAlive=true' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

Ls @ WebSocketClient.scala:37
Ks @ WebSocketClient.scala:83
Hk @ RaidFinderClient.scala:44
Ck @ Application.scala:22
Bk.init @ Application.scala:16
(anonymous function) @ (index):54

WebSocketClient.scala:37 
WebSocket connection to 'ws://gbf-raidfinder.aikats.us/ws/raids?keepAlive=true' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
Ls @ WebSocketClient.scala:37
(anonymous function) @ WebSocketClient.scala:71
bx.Ra @ AnonFunctions.scala:10
(anonymous function) @ package.scala:33
```

BTW, using in mobile phone have no problems though.
If you think that's this issue is not related with your tool, please feel free to close or delete it.
It might cause from my ISP.
Thank you.

**Comment by walfie** [comment]
When you open this url, does anything show up in the console on the right side?
http://jsbin.com/wuxinix/1/edit?js,console

I haven't heard anyone else having the same issue, so I imagine it's something on your end. Are you using any plugins/extensions that might affect it?

**Comment by majorl3oat** [comment]
Thanks for reply sir.
Nothing show up on the right side as image below.
![2](https://cloud.githubusercontent.com/assets/7145189/19294935/2eb60eac-905b-11e6-8178-88a14921d546.PNG)

BTW, just know that it can attach image so..
When I open the tools it's like this..
![4](https://cloud.githubusercontent.com/assets/7145189/19295093/6345a58c-905c-11e6-8282-69932bdcb753.PNG)

and about console in chrome.
![3](https://cloud.githubusercontent.com/assets/7145189/19294949/3d58c5e4-905b-11e6-9bec-1696eea02f2e.PNG)

For plugins/extensions, I rarely install these things.
I use safari, chrome, maxthon to open the tool though, still cannot use it.
Actually, I have 3 friends using this tool too, me and one of my friend cannot use but the other 2 can use it perfectly.

Well, If no one haven't had this issue, just close it sir. It might cause from my ISP in my country.
And I will remote to window server in other country and using it instead lol

**Comment by walfie** [comment]
Yeah it's definitely some kind of connection issue, not sure. Good luck!
