### ISSUE TITLE
My IP got blacklisted?

### ISSUE THREAD

**Issue by AranCDM** [walfie/gbf-raidfinder#87]
My problem is that I could normally open the site but it shows infinite loading screens (currently happened only on my home internet and mobile LTE.: http://i.imgur.com/OhQTaJu.png)

A few weeks ago I was unable to access the website from my home internet (It was working fine on my dorm internet.) so switched to the mobile data and it worked. Today I can't access the website using my mobile data, so I connected to a VPN and it became working again. 
Is it an IP ban and I tripped some flags?

**Comment by walfie** [comment]
I don't have any IP banning functionality in the code, and can't see any setting in Heroku, so unfortunately I don't know why this might be happening (someone else has reported something similar before: https://github.com/walfie/gbf-raidfinder/issues/69).

**Comment by AranCDM** [comment]
I'm quite sure it was the same issue, currently I have to switch from LTE to 3G in order to access the website (I still have no access to them using LTE/Home internet.). This is quite sad because this app helped me a lot on joining high attendance raids.

**Comment by walfie** [comment]
ok it looks like the issue may be because some ISPs block websocket connections on port 80, or interfere with the message in some way.

The only real way around this that I can see is to use secure websockets, but I'm running this on Heroku's free tier, which does not support this.

**Comment by KiraEnLight** [comment]
Had same problem.

Solution: Use Firefox > Install Browsec extension. So, you need 2nd browsers. Worth it.

**Comment by walfie** [comment]
You can try using this version by @laforeta which uses https: https://gbf-raidfinder.la-foret.me/
