### ISSUE TITLE
False raid names can be created using the twitter reset function.

### ISSUE THREAD

**Issue by pbwebtech** [walfie/gbf-raidfinder#98]
If you use the twitter refresh in-game and add the text
参加者募集！参戦ID：[RAID CODE] [RAID NAME]
eg
参加者募集！参戦ID：114514810
Lv100 ケルベロス
(found at https://twitter.com/megakureiXrdR/status/807071380277579776/photo/1)
it shows up in the raid listing even if the tweet is removed (image: http://i.imgur.com/3iAFJLu.png, I was testing to see how the cerberus one showed up and added a fenrir one by accident. Deleted the tweet but the listing still remains 2 days later.)

**Comment by walfie** [comment]
Thanks for the report!
